language: node_js
node_js:
  - 8
cache:
  yarn: true
  directories:
    - node_modules
script:
  - npm run build
  - npm test
deploy:
  provider: surge
  project: ./build/
  domain: fcc-camper-leaderboard.surge.sh
